development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: graylog2_development
  pool: 5
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: graylog2_production
  pool: 5
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: graylog2_test
  pool: 5
  username: root
  password:
